language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ignj/docker-cicd -f Dockerfile.dev .

script:
    - docker run -e CI=true ignj/docker-cicd npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2" #instance region
    app: "docker-react" #app name in aws
    env: "Docker-env" #from aws dashboard
    bucket_name: "elasticbeanstalk-us-west-2" #name of the s3 bucket when you create the elasticbeanstalk instance
    bucket_path: "docker-react" #same of the app name
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY